djangocms_comments/urls.py
from django.conf.urls import *

from djangocms_comments.views import SaveComment

urlpatterns = [
    url(r'^ajax/save_comment$', SaveComment.as_view(), name='djangocms_comments_save_comment'),
]

djangocms_comments/models.py
import django
from django.conf import settings

try:
    from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
except ImportError:
    from django.contrib.contenttypes.generic import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db import models
from cms.models.pluginmodel import CMSPlugin
from django.template.defaultfilters import truncatechars
from django.utils.translation import ugettext_lazy as _

MODERATED = [
    ('spam', _('Spam')),
    ('edited', _('Edited')),
    ('deleted', _('Deleted')),
]

REQUIRES_ATTENTION = [
    ('spam', _('Spam')),
    ('edited', _('Edited')),
    ('created', _('Created')),
]


class CommentsConfig(models.Model):
    name = models.CharField(max_length=32)
    open_comments = models.BooleanField(default=True)
    published_by_default = models.BooleanField(default=True)

    akismet = models.CharField(max_length=12, blank=True)

    def __str__(self):
        return self.name


class CommentsCMSPlugin(CMSPlugin):
    """AppHookConfig aware abstract CMSPlugin class for Aldryn Newsblog"""
    # avoid reverse relation name clashes by not adding a related_name
    # to the parent plugin

    config = models.ForeignKey(CommentsConfig, on_delete=models.PROTECT)

    class Meta:
        abstract = True

    def copy_relations(self, old_instance):
        self.config = old_instance.config


class Comment(models.Model):
    config = models.ForeignKey(CommentsConfig, on_delete=models.PROTECT,)

    page_type = models.ForeignKey(ContentType, on_delete=models.PROTECT, related_name='+')
    page_id = models.PositiveIntegerField()
    page = GenericForeignKey('page_type', 'page_id')

    author_type = models.ForeignKey(ContentType, on_delete=models.PROTECT, related_name='+')
    author_id = models.PositiveIntegerField()
    author = GenericForeignKey('author_type', 'author_id')

    body = models.TextField()

    requires_attention = models.CharField(blank='', max_length=16, choices=REQUIRES_ATTENTION)
    moderated = models.CharField(blank='', max_length=16, choices=MODERATED)
    moderated_reason = models.CharField(max_length=120, blank=True)
    moderated_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, blank=True, null=True)

    user_ip = models.GenericIPAddressField()
    # http://stackoverflow.com/questions/654921/how-big-can-a-user-agent-string-get
    user_agent = models.TextField()
    referrer = models.URLField(blank=True)
    published = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def is_edited(self):
        return self.updated_at.replace(second=0, microsecond=0) > self.created_at.replace(second=0, microsecond=0)

    def __str__(self):
        return u'[{}] {}'.format(self.page, truncatechars(self.body, 40))

    def __unicode__(self):
        return self.__str__()


class AnonymousAuthor(models.Model):
    username = models.CharField(max_length=32)
    email = models.EmailField()
    website = models.URLField(blank=True)
    comments = GenericRelation(Comment, object_id_field='author_id', content_type_field='author_type',
                               **{('related_name' if django.VERSION < (1, 7)
                                   else 'related_query_name'): 'anonymous_authors'})

    def __str__(self):
        return self.username

    def __unicode__(self):
        return self.username


class Comments(CommentsCMSPlugin):
    published_by_default = models.BooleanField(default=True)

djangocms_comments/templates/djangocms_comments/admin_submit_line.html
{% load i18n admin_urls %}
<div class="submit-row">
{% if show_save %}<input type="submit" value="{% trans 'Save' %}" class="default" name="_save" />{% endif %}
{% if show_delete_link %}
    {% url opts|admin_urlname:'delete' original.pk|admin_urlquote as delete_url %}
    <p class="deletelink-box">
        <a href="{% add_preserved_filters delete_url %}" class="deletelink">{% trans "Permanent Delete" %}</a></p>
{% endif %}
<input type="submit" class="{% if is_soft_deleted %}restore{% else %}delete{% endif %}" id="toggle_soft_delete"
       value="{% if is_soft_deleted %}{% trans 'Restore comment' %}{% else %}{% trans 'Soft delete' %}{% endif%}"
       name="toggle_soft_delete" />
{% if show_save_as_new %}<input type="submit" value="{% trans 'Save as new' %}" name="_saveasnew" />{% endif %}
{% if show_save_and_add_another %}<input type="submit" value="{% trans 'Save and add another' %}" name="_addanother" />{% endif %}
{% if show_save_and_continue %}<input type="submit" value="{% trans 'Save and continue editing' %}" name="_continue" />{% endif %}
</div>

djangocms_comments/templates/djangocms_comments/comment-admin-info.html
{% extends "admin/change_form.html" %}
{% load i18n comments_utils comments_admin %}
{% block field_sets %}
    <div id="author-comment-card">
        <div id="controls">
            {{ adminform.form.change_to }}
            <div class="is-moderated">
                {% if original.moderated == 'spam' %}
                {% blocktrans with moderated_by=original.moderated_by %}
                The comment has been marked as spam by {{ moderated_by }}
                {% endblocktrans %}
                {% elif original.moderated and original.published %}
                {% blocktrans with moderated_by=original.moderated_by moderated=original.get_moderated_display.lower %}
                The comment has been {{ moderated }} by {{ moderated_by }}
                {% endblocktrans %}
                {% endif %}
            </div>
        </div>
        <img src="http://www.gravatar.com/avatar/{{ original.author.email|md5 }}" class="avatar" />
        <div class="author-comment-info">
            <div>
                {% trans "Written by" %}
                <strong>{{ original.author }}</strong>
                <span title="{{ original.created_at }}">{{ original.created_at|timesince }}</span>
                {% trans "ago" %}
                {% if original.is_edited %}
                    (and edited <span title="{{ original.updated_at }}">{{ original.updated_at|timesince }}</span>
                    {% trans "ago" %})
                {% endif %}
            </div>
            <div>
                <span title="{{ original.user_agent }}">{{ user_agent }}</span>
                (ip. <a href="https://geoiptool.com/es/?ip={{ original.user_ip }}" target="_blank">
                    {{ original.user_ip }}</a>)
            </div>
            <div>
                <span>{% trans "Referrer" %}:</span>
                <a href="{{ original.referrer }}">{{ original.referrer|truncatechars:100 }}</a>
            </div>
        </div>
    </div>
    {{ block.super }}
{% endblock %}

{% block submit_buttons_bottom %}{% submit_row %}{% endblock %}

djangocms_comments/templates/djangocms_comments/comment.html
{% load comments_utils i18n %}
<div class="row comment{% if not comment.published %} unpublished{% endif %}
            {% if comment.moderated == 'spam' %} spam{% endif %}">
    <div class="col-md-3">
        <img src="http://www.gravatar.com/avatar/{{ comment.author.email|md5 }}" class="avatar" />
    </div>
    <div class="col-md-21">
        <div class="panel panel-default">
            <div class="panel-heading">
                <strong>{{ comment.author }}</strong>
                <span>{{ comment.created_at|timesince }}</span>
            </div>
            <div class="panel-body">
                {% if comment.moderated == 'deleted' and is_staff %}
                <div class="text-danger">{% trans "This comment has been deleted and users can't see it." %}</div>
                {% endif %}
                {% if comment.moderated != 'deleted' or is_staff %}
                    <pre class="{{ comment.moderated }}">{{ comment.body }}</pre>
                {% endif %}
                {% if comment.moderated == 'spam' %}
                <div class="text-danger">{% trans "This comment is spam and users can't see it." %}</div>
                {% elif comment.moderated %}
                    <div class="text-warning">
                        {% blocktrans with moderated=comment.get_moderated_display.lower %}
                        This comment has been {{ moderated }} by a moderator.
                        {% endblocktrans %}
                    </div>
                    {%if comment.moderated_reason %}
                    <div class="text-warning"><strong>{% trans "Reason:"%} </strong>{{ comment.moderated_reason }}</div>
                    {% endif %}
                {% endif %}
            </div><!-- /panel-body -->
        </div><!-- /panel panel-default -->
    </div>
</div>

djangocms_comments/templates/djangocms_comments/comment_box.html
{% load bootstrap4 comments_utils %}

<div class="comment-box{% if comment %} success-form{% endif %}">
    {% if comment %}
        <div class="comment-success">
            {% include "djangocms_comments/comment.html" with comment=comment %}
        </div>
    {% endif %}
    <form action="{% url 'djangocms_comments_save_comment' %}" method="post" class="comment-box-form">
        {% csrf_token %}
        {% if comment %}
            {% bootstrap_alert "Your comment has been sent" alert_type="success" %}
        {% endif %}
        {% if is_user %}
        <div class="row">
            <div class="col-md-24">
                <img src="http://www.gravatar.com/avatar/{{ request.user.email|md5 }}" class="avatar" />
                <div>
                    <strong>{{ request.user }}</strong>
                    {% if request.user.is_staff %}<span class="label label-primary">Staff</span>{% endif %}
                </div>
                <div>X comments</div>
            </div>
        </div>
        {% else %}
        <div class="row">
            <div class="col-md-19">
                {% bootstrap_field form.username show_label=false horizontal_label_class='col-md-0' %}
                {% bootstrap_field form.email show_label=false horizontal_label_class='col-md-0' %}
                {% bootstrap_field form.website show_label=false horizontal_label_class='col-md-0' %}
            </div>
            <div class="col-md-5">
                <img src="http://www.gravatar.com/avatar/?s=150&d=mm" class="avatar dynamic-gravatar" />
            </div>
        </div>
        {% endif %}
        <div class="row">
            {% bootstrap_form_errors form %}
            <div class="col-md-24">{% bootstrap_field form.body show_label=false %}</div>
        </div>
        {{ form.config_id }}
        {{ form.page_type }}
        {{ form.page_id }}
        {% bootstrap_button "Submit" button_type="submit" %}
    </form>
</div>

djangocms_comments/templates/djangocms_comments/comments.html
{% load staticfiles sekizai_tags cms_tags %}
{% if use_src %}
    {% addtoblock "js" %}
    <script src="{% static 'djangocms_comments/src/libs/autosize/dist/autosize.js' %}"></script>
    <script src="{% static 'djangocms_comments/src/libs/blueimp-md5/js/md5.min.js' %}"></script>
    <script src="{% static 'djangocms_comments/src/js/comments.js' %}"></script>
    {% endaddtoblock %}
{% else %}
    {% addtoblock "js" %}
    <script src="{% static 'djangocms_comments/dist/js/comments.min.js' %}"></script>
    {% endaddtoblock %}
{% endif %}

{% if use_src %}
    {% addtoblock "css" %}
    <link rel="stylesheet" href="{% static 'djangocms_comments/src/css/comments.css' %}">
    {% endaddtoblock %}
{% else %}
    {% addtoblock "css" %}
    <link rel="stylesheet" href="{% static 'djangocms_comments/dist/css/comments.css' %}">
    {% endaddtoblock %}
{% endif %}
<div class="comments-and-box-plugin">
    <h2>Comments</h2>
    <div class="comments-list">
        {% for comment in comments.all %}
            {% render_model_block comment %}
                {% include "djangocms_comments/comment.html" %}
            {% endrender_model_block%}
        {% endfor %}
    </div>
    {% include "djangocms_comments/comment_box.html" %}
</div>